# Generated by Django 4.2.6 on 2023-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('engine_capacity', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
    ]
